[!10][BUG] Read log files that delete all the content from the very beginning
# Why is this needed?

The current code breaks when computing metrics for cases in which all the text is replaced at the beginning of a talk with exception:

```
Traceback (most recent call last):
  File ".../simulstream_score_latency", line 8, in <module>
    sys.exit(cli_main())
             ^^^^^^^^^^
  File ".../simulstream/metrics/score_latency.py", line 126, in cli_main
    main(scorer_cls, args)
  File ".../simulstream/metrics/score_latency.py", line 62, in main
    output_with_latency = log_reader.final_outputs_and_latencies()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../simulstream/metrics/readers.py", line 218, in final_outputs_and_latencies
    if ending_word_before_update != new_output.last_word():
                                    ^^^^^^^^^^^^^^^^^^^^^^
  File ".../simulstream/metrics/readers.py", line 98, in last_word
    return self.text_items("word")[-1]
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
```

# What does the MR changes?

Fixes the bug.

# How was the MR tested?

Added UTs.